//go:build linux

package gpu

import (
	_ "embed"
	"testing"
)

// smokePTX is the build artifact of smoke.cu, regenerated by ./build_ptx.sh.
//
//go:embed testdata/smoke.ptx
var smokePTX []byte

// TestCUDA_smokeAdd proves the cgo-free CUDA path works end to end from aikit —
// the exact twin of TestMetal_smokeAdd: reach the device, JIT the PTX, build a
// pipeline, upload buffers, dispatch, read the result back.
func TestCUDA_smokeAdd(t *testing.T) {
	d, err := CreateSystemDefaultDevice()
	if err != nil {
		t.Skipf("no CUDA device: %v", err)
	}
	defer d.ReleaseObjects()
	t.Logf("device: %s", d.Name())

	lib, err := d.CompileLibrary(smokePTX)
	if err != nil {
		t.Fatalf("CompileLibrary: %v", err)
	}
	p, err := d.NewComputePipeline(lib, "vadd")
	if err != nil {
		t.Fatalf("pipeline: %v", err)
	}
	q := d.NewCommandQueue()
	a := NewBufferOf(d, []float32{1, 2, 3, 4, 5})
	b := NewBufferOf(d, []float32{10, 20, 30, 40, 50})
	out := d.NewBufferLen(5)
	n := NewBufferOf(d, []uint32{5})
	if err := q.Run1D(p, 5, 5, a, b, out, n); err != nil {
		t.Fatalf("Run1D: %v", err)
	}

	got := make([]float32, 5)
	if err := Download(out, got); err != nil {
		t.Fatalf("Download: %v", err)
	}
	want := []float32{11, 22, 33, 44, 55}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("out[%d] = %v, want %v", i, got[i], want[i])
		}
	}
	t.Logf("vadd result: %v", got)
}

// TestCUDA_tailBlockGuard covers the one semantic difference from Metal that a
// kernel author can get wrong: a CUDA launch rounds up to whole blocks, so with
// n=5 and tg=4 the second block runs threads 4..7 — three of them past the end.
// The kernel's bounds check is what keeps that from writing out of range, and a
// dispatch whose thread count is NOT a multiple of the block size is the case that
// exercises it. (Metal's dispatchThreads launches exactly n and never does.)
func TestCUDA_tailBlockGuard(t *testing.T) {
	d, err := CreateSystemDefaultDevice()
	if err != nil {
		t.Skipf("no CUDA device: %v", err)
	}
	defer d.ReleaseObjects()

	lib, err := d.CompileLibrary(smokePTX)
	if err != nil {
		t.Fatalf("CompileLibrary: %v", err)
	}
	p, err := d.NewComputePipeline(lib, "vadd")
	if err != nil {
		t.Fatalf("pipeline: %v", err)
	}
	q := d.NewCommandQueue()

	// out is allocated with 3 elements of slack, pre-filled with a sentinel. If the
	// tail block wrote past n, the sentinel would be clobbered.
	const n, slack = 5, 3
	a := NewBufferOf(d, []float32{1, 2, 3, 4, 5})
	b := NewBufferOf(d, []float32{10, 20, 30, 40, 50})
	out := NewBufferOf(d, []float32{-1, -1, -1, -1, -1, -7, -7, -7})
	nbuf := NewBufferOf(d, []uint32{n})
	if err := q.Run1D(p, n, 4, a, b, out, nbuf); err != nil { // 4 ∤ 5 ⇒ a partial tail block
		t.Fatalf("Run1D: %v", err)
	}

	got := make([]float32, n+slack)
	if err := Download(out, got); err != nil {
		t.Fatalf("Download: %v", err)
	}
	want := []float32{11, 22, 33, 44, 55, -7, -7, -7}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("out[%d] = %v, want %v (tail block overran n)", i, got[i], want[i])
		}
	}
}

// TestCUDA_ledgerDrains is the leak gate: every buffer, module and stream the
// Device hands out is on its ledger, and ReleaseObjects drives both counters to
// zero. gocudrv cannot free a Buffer after its Context closes, so a buffer left on
// the ledger at Close is a permanent device-memory leak — the CUDA counterpart of
// metal_leak_test.go's purego/no-ARC leak.
func TestCUDA_ledgerDrains(t *testing.T) {
	d, err := CreateSystemDefaultDevice()
	if err != nil {
		t.Skipf("no CUDA device: %v", err)
	}
	lib, err := d.CompileLibrary(smokePTX)
	if err != nil {
		d.ReleaseObjects()
		t.Fatalf("CompileLibrary: %v", err)
	}
	if _, err := d.NewComputePipeline(lib, "vadd"); err != nil {
		d.ReleaseObjects()
		t.Fatalf("pipeline: %v", err)
	}
	_ = d.NewCommandQueue()
	scratch := d.NewBufferLen(16)
	NewBufferOf(d, make([]int8, 32))

	allocs, objs := d.LedgerLen()
	if allocs != 2 || objs != 2 { // 2 buffers; module + stream
		t.Fatalf("ledger = (%d allocs, %d objs), want (2, 2)", allocs, objs)
	}

	// ReleaseBuf takes one buffer off the ledger without disturbing the rest, so a
	// later ReleaseAll cannot double-free it.
	d.ReleaseBuf(scratch)
	if allocs, _ = d.LedgerLen(); allocs != 1 {
		t.Errorf("after ReleaseBuf: %d allocs, want 1", allocs)
	}

	d.ReleaseObjects()
	if allocs, objs = d.LedgerLen(); allocs != 0 || objs != 0 {
		t.Errorf("after ReleaseObjects: (%d allocs, %d objs), want (0, 0)", allocs, objs)
	}
	d.ReleaseObjects() // idempotent — a double Close must not panic
}
