package ner

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/townsendmerino/aikit/embed"
)

// gliner2_golden.json — generated by scripts/oracle/pin_gliner2.py from gliner2's own
// WhitespaceTokenSplitter and the HF fast tokenizer.
type gliner2Golden struct {
	SplitCases []struct {
		Text   string `json:"text"`
		Tokens []struct {
			Text  string `json:"text"`
			Start int    `json:"start"`
			End   int    `json:"end"`
		} `json:"tokens"`
	} `json:"split_cases"`
	TokenizeCases []struct {
		Words []string `json:"words"`
		IDs   []int32  `json:"ids"`
		First []int32  `json:"first"`
	} `json:"tokenize_cases"`
	PromptCases []struct {
		Labels  []string `json:"labels"`
		IDs     []int32  `json:"ids"`
		Markers []int    `json:"markers"`
	} `json:"prompt_cases"`
	ClassificationCases []struct {
		Text            string            `json:"text"`
		Task            string            `json:"task"`
		Labels          []string          `json:"labels"`
		IDs             []int32           `json:"input_ids"`
		MarkerPositions []int             `json:"marker_positions"`
		Decoded         map[string]string `json:"decoded"`
	} `json:"classification_cases"`
	ExtractCases []struct {
		Text             string      `json:"text"`
		Labels           []string    `json:"labels"`
		IDs              []int32     `json:"input_ids"`
		WordPositions    []int       `json:"word_positions"`
		MarkerPositions  []int       `json:"marker_positions"`
		TextStates       [][]float32 `json:"text_states"`
		QueryStates      [][]float32 `json:"query_states"`
		StartLogits      [][]float32 `json:"start_logits"`
		EndLogits        [][]float32 `json:"end_logits"`
		InsideLogits     [][]float32 `json:"inside_logits"`
		NullLogits       []float32   `json:"null_logits"`
		CandidateIndices [][][2]int  `json:"candidate_indices"`
		CandidateValid   [][]bool    `json:"candidate_valid"`
		PairLogits       [][]float32 `json:"pair_logits"` // [Q][C]
		Decoded          struct {
			Entities map[string][]struct {
				Text       string  `json:"text"`
				Confidence float64 `json:"confidence"`
				Start      int     `json:"start"`
				End        int     `json:"end"`
			} `json:"entities"`
		} `json:"decoded"`
	} `json:"extract_cases"`
}

func loadGLiNER2Golden(t *testing.T) *gliner2Golden {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "testdata", "gliner2_golden.json"))
	if err != nil {
		if os.IsNotExist(err) {
			t.Skip("testdata/gliner2_golden.json missing — run scripts/oracle/pin_gliner2.py")
		}
		t.Fatal(err)
	}
	var g gliner2Golden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	return &g
}

// gliner2Dir is the GLiNER2 boundary checkpoint (fastino/gliner2.5-multi-v1).
const gliner2Dir = "../testdata/gliner-multi-v2.5"

func loadGLiNER2Fixture(t *testing.T) *GLiNER2 {
	t.Helper()
	if _, err := os.Stat(gliner2Dir + "/model.safetensors"); err != nil {
		t.Skipf("no gliner2 checkpoint at %s — download fastino/gliner2.5-multi-v1 (see testdata/README.md)", gliner2Dir)
	}
	m, err := LoadGLiNER2(gliner2Dir)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = m.Close() })
	return m
}

// TestGLiNER2_split pins SplitWords2 against gliner2's WhitespaceTokenSplitter:
// token text (lowercased by the reference), plus the byte offsets re-sliced from
// the original to prove the char→byte conversion lands on the same substrings.
func TestGLiNER2_split(t *testing.T) {
	g := loadGLiNER2Golden(t)
	for ci, c := range g.SplitCases {
		got := SplitWords2(c.Text)
		if len(got) != len(c.Tokens) {
			t.Errorf("case %d (%q): %d words, want %d", ci, c.Text, len(got), len(c.Tokens))
			continue
		}
		for i, want := range c.Tokens {
			w := got[i]
			// The golden's start/end are CHARACTER offsets (Python str); convert
			// before re-slicing, same as the v1 parity gate.
			wStart, wEnd := charToByte(c.Text, want.Start), charToByte(c.Text, want.End)
			if w.Text != want.Text || w.Start != wStart || w.End != wEnd {
				t.Errorf("case %d word %d = %q [%d,%d), want %q [%d,%d)",
					ci, i, w.Text, w.Start, w.End, want.Text, wStart, wEnd)
			}
		}
	}
}

func TestGLiNER2LimitWordsCapsHeadInput(t *testing.T) {
	words := []Word{{Text: "a"}, {Text: "b"}, {Text: "c"}, {Text: "d"}}
	got := limitWords(words, 2)
	if len(got) != 2 || got[0].Text != "a" || got[1].Text != "b" {
		t.Fatalf("limitWords = %+v, want the first two words", got)
	}
}

func TestGLiNER2MultiLabelControlsDuplicateBoundaries(t *testing.T) {
	grouped := [][]g2Scored{
		{{Start: 1, End: 3, Score: 0.7}},
		{{Start: 1, End: 3, Score: 0.9}},
	}
	single := selectGrouped(grouped, "flat", false)
	if len(single) != 1 || single[0].Query != 1 {
		t.Fatalf("single-label selection = %+v, want only the higher-scoring query 1", single)
	}
	multi := selectGrouped(grouped, "flat", true)
	if len(multi) != 2 || multi[0].Query != 0 || multi[1].Query != 1 {
		t.Fatalf("multi-label selection = %+v, want both queries in declaration order", multi)
	}
}

// TestGLiNER2_tokenizer pins per-word tokenization of the checkpoint's
// tokenizer.json through embed.LoadTokenizer against HF's fast tokenizer.
func TestGLiNER2_tokenizer(t *testing.T) {
	g := loadGLiNER2Golden(t)
	tok, err := embed.LoadTokenizer(filepath.Join("..", "testdata", "gliner-multi-v2.5", "tokenizer.json"))
	if err != nil {
		t.Skipf("X: %v", err)
	}
	for ci, c := range g.TokenizeCases {
		// The reference loops word-by-word and records each word's first-id
		// offset BEFORE extending, so an empty word yields offset `len(ids)`
		// rather than -1 — replicate that here instead of using EncodeWords,
		// whose -1-for-empty convention the real forward handles separately.
		var ids []int32
		first := make([]int32, 0, len(c.Words))
		for _, w := range c.Words {
			sub := tok.Encode(w)
			first = append(first, int32(len(ids)))
			ids = append(ids, sub...)
		}
		if len(ids) != len(c.IDs) || len(first) != len(c.First) {
			t.Fatalf("case %d: ids=%d/%d first=%d/%d", ci,
				len(ids), len(c.IDs), len(first), len(c.First))
		}
		for i := range ids {
			if ids[i] != c.IDs[i] {
				t.Errorf("case %d ids[%d]=%d want %d", ci, i, ids[i], c.IDs[i])
			}
		}
		for i := range first {
			if first[i] != c.First[i] {
				t.Errorf("case %d first[%d]=%d want %d", ci, i, first[i], c.First[i])
			}
		}
	}
}

// TestGLiNER2_promptLayout pins the schema prompt's token ids and [E] marker
// positions — the same load-bearing pin as the v1 prompt-layout gate, because a
// mis-assembled prompt mis-aligns every query downstream.
func TestGLiNER2_promptLayout(t *testing.T) {
	g := loadGLiNER2Golden(t)
	m := loadGLiNER2Fixture(t)
	for ci, c := range g.PromptCases {
		ids, markers := m.buildPrompt(c.Labels)
		// The golden includes the trailing [SEP_TEXT] separator.
		ids = append(ids, m.sepTextID)
		if len(ids) != len(c.IDs) || len(markers) != len(c.Markers) {
			t.Fatalf("case %d: ids=%d/%d markers=%d/%d", ci,
				len(ids), len(c.IDs), len(markers), len(c.Markers))
		}
		for i := range ids {
			if ids[i] != c.IDs[i] {
				t.Errorf("case %d ids[%d]=%d want %d", ci, i, ids[i], c.IDs[i])
			}
		}
		for i := range markers {
			if markers[i] != c.Markers[i] {
				t.Errorf("case %d markers[%d]=%d want %d", ci, i, markers[i], c.Markers[i])
			}
		}
	}
	if m.pID != 250104 || m.eID != 250106 || m.lID != 250108 ||
		m.sepTextID != 250103 || m.sepStructID != 250102 {
		t.Errorf("special ids drifted: P=%d E=%d L=%d SEP_TEXT=%d SEP_STRUCT=%d",
			m.pID, m.eID, m.lID, m.sepTextID, m.sepStructID)
	}
}

// flat3 flattens [X][Y][Z] float tensors.
func flat2(t [][]float32) []float32 {
	var out []float32
	for _, a := range t {
		out = append(out, a...)
	}
	return out
}

// maxAbsDiff reports the largest |a-b| and the first index exceeding tol.
func maxAbsDiff(a, b []float32, tol float64) (float64, int) {
	worst := 0.0
	firstBad := -1
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := range n {
		d := math.Abs(float64(a[i] - b[i]))
		if d > worst {
			worst = d
		}
		if d > tol && firstBad < 0 {
			firstBad = i
		}
	}
	return worst, firstBad
}

// TestGLiNER2_forward pins the whole boundary forward — input ids, pooled
// states, marginals, candidate pool, pair logits — against the gliner2 library
// (scripts/oracle/pin_gliner2.py, extract_cases). The candidate SET must match
// exactly: pool construction is deterministic, so any index disagreement is a
// porting bug, not noise.
func TestGLiNER2_forward(t *testing.T) {
	g := loadGLiNER2Golden(t)
	m := loadGLiNER2Fixture(t)
	const tol = 5e-3

	for ci, c := range g.ExtractCases {
		core, err := m.encodeCore(c.Text, c.Labels, false)
		if err != nil {
			t.Fatalf("case %d: %v", ci, err)
		}
		if len(core.ids) != len(c.IDs) {
			t.Fatalf("case %d: %d input ids, want %d", ci, len(core.ids), len(c.IDs))
		}
		for i := range core.ids {
			if core.ids[i] != c.IDs[i] {
				t.Fatalf("case %d ids[%d]=%d want %d", ci, i, core.ids[i], c.IDs[i])
			}
		}
		if len(core.wordPos) != len(c.WordPositions) || len(core.markerPos) != len(c.MarkerPositions) {
			t.Fatalf("case %d: words %d/%d markers %d/%d", ci,
				len(core.wordPos), len(c.WordPositions), len(core.markerPos), len(c.MarkerPositions))
		}
		for i := range core.wordPos {
			if core.wordPos[i] != c.WordPositions[i] {
				t.Fatalf("case %d wordPos[%d]=%d want %d", ci, i, core.wordPos[i], c.WordPositions[i])
			}
		}
		for i := range core.markerPos {
			if core.markerPos[i] != c.MarkerPositions[i] {
				t.Fatalf("case %d markerPos[%d]=%d want %d", ci, i, core.markerPos[i], c.MarkerPositions[i])
			}
		}

		H := m.backbone.HiddenDim()
		if d, bad := maxAbsDiff(core.text, flat2(c.TextStates), tol); d > tol {
			t.Fatalf("case %d text_states[%d] diff %g", ci, bad/H, d)
		}
		if d, bad := maxAbsDiff(core.queries, flat2(c.QueryStates), tol); d > tol {
			t.Fatalf("case %d query_states[%d] diff %g", ci, bad/H, d)
		}

		marg, pool, scores, nullLogits, err := m.forwardCore(core)
		if err != nil {
			t.Fatal(err)
		}
		if d, bad := maxAbsDiff(marg.Start, flat2(c.StartLogits), tol); d > tol {
			t.Fatalf("case %d start_logits[%d] diff %g", ci, bad, d)
		}
		if d, bad := maxAbsDiff(marg.End, flat2(c.EndLogits), tol); d > tol {
			t.Fatalf("case %d end_logits[%d] diff %g", ci, bad, d)
		}
		if d, bad := maxAbsDiff(marg.Inside, flat2(c.InsideLogits), tol); d > tol {
			t.Fatalf("case %d inside_logits[%d] diff %g", ci, bad, d)
		}
		if len(nullLogits) != len(c.NullLogits) {
			t.Fatalf("case %d: %d null logits, want %d", ci, len(nullLogits), len(c.NullLogits))
		}
		for i := range nullLogits {
			if math.Abs(float64(nullLogits[i]-c.NullLogits[i])) > tol {
				t.Fatalf("case %d null_logits[%d]=%g want %g", ci, i, nullLogits[i], c.NullLogits[i])
			}
		}

		// Candidate set: exact indices + validity (deterministic by design).
		nValid := 0
		for _, v := range c.CandidateValid[0] { // the pool is query-agnostic; row 0 suffices
			if v {
				nValid++
			}
		}
		gotValid := 0
		for _, v := range pool.Valid {
			if v {
				gotValid++
			}
		}
		if gotValid != nValid {
			t.Fatalf("case %d: %d valid candidates, want %d", ci, gotValid, nValid)
		}
		for q := range marg.Q {
			for c2 := range len(pool.Indices) {
				if !c.CandidateValid[q][c2] {
					continue
				}
				if pool.Indices[c2] != c.CandidateIndices[q][c2] {
					t.Fatalf("case %d candidate[%d] = %v, want %v", ci, c2,
						pool.Indices[c2], c.CandidateIndices[q][c2])
				}
				want := c.PairLogits[q][c2]
				if math.Abs(float64(scores[c2*marg.Q+q]-want)) > tol {
					t.Fatalf("case %d pair_logits[q=%d c=%d]=%g want %g", ci, q, c2,
						scores[c2*marg.Q+q], want)
				}
			}
		}
	}
}

// TestGLiNER2_parity certifies the decoded entity sets and surfaces against the
// gliner2 reference. Character offsets are converted to byte offsets, as in the
// v1 gate.
func TestGLiNER2_parity(t *testing.T) {
	g := loadGLiNER2Golden(t)
	m := loadGLiNER2Fixture(t)

	for ci, c := range g.ExtractCases {
		got, err := m.Predict(c.Text, c.Labels, Opts{})
		if err != nil {
			t.Fatal(err)
		}
		var want []Entity
		for _, label := range c.Labels {
			for _, e := range c.Decoded.Entities[label] {
				want = append(want, Entity{
					Text:  e.Text,
					Label: label,
					Start: charToByte(c.Text, e.Start),
					End:   charToByte(c.Text, e.End),
					Score: e.Confidence,
				})
			}
		}
		if len(got) != len(want) {
			t.Errorf("case %d (%q): %d entities, want %d", ci, c.Text, len(got), len(want))
			continue
		}
		for i := range want {
			e, w := got[i], want[i]
			if e.Text != w.Text || e.Label != w.Label || e.Start != w.Start || e.End != w.End {
				t.Errorf("case %d entity %d = %+v, want %+v", ci, i, e, w)
			}
			if math.Abs(e.Score-w.Score) > 1e-2 {
				t.Errorf("case %d entity %d score %.6f, want %.6f", ci, i, e.Score, w.Score)
			}
			if c.Text[e.Start:e.End] != e.Text {
				t.Errorf("case %d entity %d surface %q does not re-slice", ci, i, e.Text)
			}
		}
	}
}

// TestGLiNER2_classify pins the classification prompt, ids, and decoded label.
func TestGLiNER2_classify(t *testing.T) {
	g := loadGLiNER2Golden(t)
	m := loadGLiNER2Fixture(t)
	for ci, c := range g.ClassificationCases {
		got, err := m.Classify(c.Text, c.Task, c.Labels, false)
		if err != nil {
			t.Fatal(err)
		}
		// pin the prompt layout against the golden ids
		ids, markers := m.buildClassifyPrompt(c.Task, c.Labels)
		ids = append(ids, m.sepTextID)
		_ = ids
		if len(markers) != len(c.MarkerPositions) {
			t.Fatalf("case %d: %d markers, want %d", ci, len(markers), len(c.MarkerPositions))
		}
		best := got[0]
		for _, r := range got[1:] {
			if r.Prob > best.Prob {
				best = r
			}
		}
		want := c.Decoded[c.Task]
		if best.Label != want {
			t.Errorf("case %d: label %q (%.4f), want %q", ci, best.Label, best.Prob, want)
		}
	}
}
