//go:build linux

// Package anncuda registers a native-CUDA implementation of ann.Backend, so an
// ann.FlatI8 that calls EnableGPU scores its int8 corpus GEMV on the GPU. It is
// the Linux mirror of gpu/annmetal (docs/task-native-gpu.md, Phase 1b) — same
// seam, same two kernels, same parity gate — built on the CUDA half of aikit's
// device substrate (gpu/cuda.go).
//
// Importing this package is the opt-in: aikit's core `ann` never imports `gpu`,
// so the default build stays pure-Go CPU.
//
// Two kernels (gemv_w8a8.cu, PTX-embedded): gemv_w8a8 scores ONE query against the
// whole index (FlatI8.Query), gemm_w8a8 scores M queries in one launch
// (FlatI8.QueryBatch). Both compute the exact int32 dot of the host-quantized int8
// query against each row, then the query/row rescale — the same value the CPU
// linalg.MatmulBTW8A8 produces, so GPU and CPU rank identically. The kernels are
// intentionally minimal and correctness-only; the tuned decode kernels are
// goinfer's and stay there.
package anncuda

import (
	_ "embed"
	"fmt"
	"math"
	"sync"

	"github.com/townsendmerino/aikit/ann"
	gpu "github.com/townsendmerino/aikit/gpu"
)

// w8a8PTX is the build artifact of gemv_w8a8.cu, regenerated by ../build_ptx.sh.
// Embedding PTX (rather than compiling CUDA C at run time, the way the Metal side
// compiles MSL) is what keeps the runtime toolkit-free: only libcuda is needed,
// and the driver JITs this.
//
//go:embed testdata/gemv_w8a8.ptx
var w8a8PTX []byte

type cudaBackend struct {
	dev  *gpu.Device
	q    gpu.Queue
	gemv gpu.Pipeline // one query  × N rows (FlatI8.Query)
	gemm gpu.Pipeline // M queries × N rows (FlatI8.QueryBatch) — naive, kept as reference
	// gemmT is gpu's TILED W8A8 GEMM, reused rather than duplicated here: its
	// (A, aScale, B, bScale, C, M, N, K) is exactly this backend's
	// (qi8, qscale, codes, scales, out, M, N, K). Bit-identical to gemm — int32 sums
	// are associative, so re-chunking K cannot change a score.
	gemmT gpu.Pipeline
	topk  gpu.Pipeline // per-query top-k on the device (avoids the M×N readback)
}

// init reaches CUDA and registers the backend. If there is no CUDA device (no
// libcuda, no GPU) or the PTX fails to load, it registers nothing — ann.FlatI8
// then stays on the CPU and EnableGPU returns "no backend".
func init() {
	dev, err := gpu.CreateSystemDefaultDevice()
	if err != nil {
		return
	}
	lib, err := dev.CompileLibrary(w8a8PTX)
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	gemv, err := dev.NewComputePipeline(lib, "gemv_w8a8")
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	gemm, err := dev.NewComputePipeline(lib, "gemm_w8a8")
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	topk, err := dev.NewComputePipeline(lib, "topk_rows")
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	// The tiled GEMM lives in gpu's ViT module; loading it here reuses that kernel
	// instead of keeping a second copy of the same 16×16 tile in this package.
	vit, err := dev.NewViT()
	if err != nil {
		dev.ReleaseObjects()
		return
	}
	ann.RegisterBackend(&cudaBackend{
		dev: dev, q: dev.NewCommandQueue(),
		gemv: gemv, gemm: gemm, gemmT: vit.GEMMW8A8Tiled, topk: topk,
	})
}

func (b *cudaBackend) Name() string { return "cuda" }

// NewI8Index uploads the int8 codes + scales resident on the device and allocates
// the reusable per-query scratch (quantized query, query scale, output, and the
// row count the kernels bounds-check against).
func (b *cudaBackend) NewI8Index(bq []int8, scales []float32, n, dim int) (idx ann.I8Index, err error) {
	if n <= 0 || dim <= 0 {
		return nil, fmt.Errorf("gpu: empty int8 index (n=%d dim=%d)", n, dim)
	}
	if len(bq) != n*dim || len(scales) != n {
		return nil, fmt.Errorf("gpu: int8 index shape mismatch (bq %d, scales %d, n=%d dim=%d)", len(bq), len(scales), n, dim)
	}
	// A corpus upload is the one allocation here big enough to exhaust device
	// memory, and the device layer reports OOM as a loud panic (MustBuf) rather
	// than a silently unusable buffer. Recover it into an error so EnableGPU
	// declines and the index keeps scoring on the CPU — the right answer for OOM.
	defer func() {
		if r := recover(); r != nil {
			idx, err = nil, fmt.Errorf("gpu: device upload failed: %v", r)
		}
	}()
	x := &cudaI8Index{
		b:      b,
		n:      n,
		dim:    dim,
		codes:  b.dev.NewBufferInt8(bq),
		scales: b.dev.NewBufferFloats(scales),
		qi8:    b.dev.NewBufferInt8(make([]int8, dim)),
		qscale: b.dev.NewBufferFloats([]float32{0}),
		kbuf:   b.dev.NewBufferU32(uint32(dim)),
		nbuf:   b.dev.NewBufferU32(uint32(n)),
		out:    b.dev.NewBufferLen(n),
		hq:     make([]int8, dim),
	}
	return x, nil
}

type cudaI8Index struct {
	b      *cudaBackend
	n, dim int
	codes  gpu.Buffer // [n*dim] int8 (resident)
	scales gpu.Buffer // [n] f32
	qi8    gpu.Buffer // [dim] int8 (reused per query)
	qscale gpu.Buffer // [1] f32 (reused)
	kbuf   gpu.Buffer // [1] u32 — dim
	nbuf   gpu.Buffer // [1] u32 — row count, the kernel's launch bound
	out    gpu.Buffer // [n] f32 (reused)
	hq     []int8     // host staging for the quantized query (reused)
	mu     sync.Mutex
}

// Score dynamically quantizes q on the host (byte-identical to linalg's
// quantizeRowInt8), uploads it, dispatches the GEMV, and copies the scores back.
// Serialized: the reused scratch buffers are per-index, and one stream runs
// serially.
//
// Where the Metal path writes the quantized query straight into the buffer's UMA
// mapping, CUDA memory is not host-visible — hence the host staging slice plus an
// explicit upload (gpu/cuda.go, divergence 1).
func (x *cudaI8Index) Score(q []float32, dst []float32) error {
	if len(q) != x.dim {
		return fmt.Errorf("gpu: query dim %d != index dim %d", len(q), x.dim)
	}
	if len(dst) != x.n {
		return fmt.Errorf("gpu: dst len %d != index n %d", len(dst), x.n)
	}
	x.mu.Lock()
	defer x.mu.Unlock()
	qscale := quantizeRowInt8(q, x.hq)
	if err := x.qi8.WriteInt8s(x.hq); err != nil {
		return err
	}
	if err := x.qscale.WriteFloats([]float32{qscale}); err != nil {
		return err
	}
	// gemv_w8a8 is WARP-per-row, not thread-per-row: 32 lanes cooperate on one row so
	// their loads coalesce. The dispatch is therefore n*32 threads, and the kernel's
	// own bound check compares the global WARP index against n.
	if err := x.b.q.Run1D(x.b.gemv, x.n*32, 256, x.codes, x.qi8, x.scales, x.kbuf, x.qscale, x.out, x.nbuf); err != nil {
		return err
	}
	return x.out.ReadFloats(dst)
}

// ScoreBatch scores M = len(queries) queries against all N rows in a single
// dispatch of the batched GEMM — the throughput win over calling Score in a loop.
// dst is [M*N] row-major (dst[m*N+j]). Per-call scratch is allocated and released
// each call: batch queries are the infrequent path, so this stays simple rather
// than caching an M-sized arena.
func (x *cudaI8Index) ScoreBatch(queries [][]float32, dst []float32) (err error) {
	M := len(queries)
	if M == 0 {
		return nil
	}
	N, K := x.n, x.dim
	if len(dst) != M*N {
		return fmt.Errorf("gpu: batch dst len %d != M*N %d", len(dst), M*N)
	}
	qi8 := make([]int8, M*K)
	qscale := make([]float32, M)
	for m, q := range queries {
		if len(q) != K {
			return fmt.Errorf("gpu: batch query %d dim %d != index dim %d", m, len(q), K)
		}
		qscale[m] = quantizeRowInt8(q, qi8[m*K:(m+1)*K])
	}
	x.mu.Lock()
	defer x.mu.Unlock()
	// Same OOM-to-error contract as NewI8Index: an M×N output can be large.
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("gpu: batch scratch allocation failed: %v", r)
		}
	}()
	qi8Buf := x.b.dev.NewBufferInt8(qi8)
	qscaleBuf := x.b.dev.NewBufferFloats(qscale)
	outBuf := x.b.dev.NewBufferLen(M * N)
	defer func() {
		for _, b := range []gpu.Buffer{qi8Buf, qscaleBuf, outBuf} {
			x.b.dev.ReleaseBuf(b)
		}
	}()
	if err := x.launchGEMM(qi8Buf, qscaleBuf, outBuf, M, N, K); err != nil {
		return err
	}
	if err := x.b.q.Sync(); err != nil {
		return err
	}
	return outBuf.ReadFloats(dst)
}

// Close releases this index's device buffers (the shared device stays alive for
// other indexes; the process holds one CUDA context).
func (x *cudaI8Index) Close() error {
	for _, b := range []gpu.Buffer{x.codes, x.scales, x.qi8, x.qscale, x.kbuf, x.nbuf, x.out} {
		x.b.dev.ReleaseBuf(b)
	}
	return nil
}

// quantizeRowInt8 replicates linalg's (unexported) per-row int8 quantizer exactly:
// scale = maxAbs/127, dst[k] = round(q[k]/scale) clamped to ±127; all-zero input →
// scale 0. Kept byte-identical so the GPU int8 dot equals the CPU one. (Identical
// to gpu/annmetal's copy — same reference, and the two backends never build
// together.)
func quantizeRowInt8(a []float32, dst []int8) (scale float32) {
	var maxAbs float32
	for _, v := range a {
		if v < 0 {
			v = -v
		}
		if v > maxAbs {
			maxAbs = v
		}
	}
	if maxAbs == 0 {
		for k := range dst {
			dst[k] = 0
		}
		return 0
	}
	scale = maxAbs / 127
	inv := 1.0 / scale
	for k, v := range a {
		x := math.Round(float64(v * inv))
		if x > 127 {
			x = 127
		} else if x < -127 {
			x = -127
		}
		dst[k] = int8(x)
	}
	return scale
}

// topkMinN is the row count below which TopKBatch declines to the score-then-host-topk
// path. It is DERIVED FROM THIS BOX's sweep, not copied from Metal: the second launch
// has to earn back more than the readback it saves, and CUDA's launch floor (~µs) sits
// two orders of magnitude below Metal's command-buffer floor (~250 µs), so the two
// platforms cross over in different places. See docs/BENCH-gpu-results.md.
const topkMinN = 50_000

// topkMinBatch is the second half of the device-top-k gate, and it is about OCCUPANCY
// rather than transfer. topk_rows runs ONE BLOCK PER QUERY, so a batch of 1 occupies a
// single SM of 40 while the rest of the card idles — and the readback it saves at that
// size (N floats) is small anyway. Measured: at N=100k, batch=1 went 0.79x -> 0.43x with
// device top-k unconditionally on, while batch=8 went 0.88x -> 3.93x. So the kernel
// needs a real batch behind it.
const topkMinBatch = 8

// gemmTileMinM is where the TILED GEMM starts to pay. It stages a 16x16 output tile, so
// a batch of M < 16 leaves (16-M)/16 of every block's rows idle — at M=1 that is 15/16
// of the threads doing nothing, which is why batch=1 REGRESSED when the tiled kernel was
// switched on unconditionally (N=10k: 1.32x -> 1.12x). The naive kernel parallelises over
// M*N and has no such waste, so it stays the right choice for thin batches. This is the
// opposite of the usual "tiling always wins" intuition and only shows up at small M.
const gemmTileMinM = 2

// TopKBatch implements ann.I8TopKIndex: score the batch on the device, select each
// query's top-k THERE, and return only M*k hits.
//
// The point is the readback. ScoreBatch must copy the whole M×N score matrix to the
// host — at N=1e6, batch=256 that is ~1 GB over PCIe, and on a discrete GPU that is a
// real transfer, not the near-free UMA view Metal enjoys. Selecting on-device turns it
// into M*k.
//
// It DECLINES (returns an error, which FlatI8.QueryBatch treats as "use the scoring
// path") for small N, for k outside the range the kernel implements, and on any device
// failure. The fallback's result is identical, so declining is always safe.
//
// The device selection reproduces ann.topHits's order exactly — score DESC, index ASC
// on ties — so this returns the SAME hits the CPU would, not merely a plausible set.
func (x *cudaI8Index) TopKBatch(queries [][]float32, k int) (hits [][]ann.Hit, err error) {
	M := len(queries)
	if M == 0 {
		return nil, nil
	}
	N, K := x.n, x.dim
	// k <= 0 or k >= N is topHits's full-sort path, which this kernel does not
	// implement; below topkMinN the extra launch costs more than the readback it
	// saves. Both decline rather than approximate.
	if k <= 0 || k >= N || N < topkMinN || M < topkMinBatch {
		return nil, fmt.Errorf("gpu: TopKBatch declined (k=%d n=%d batch=%d)", k, N, M)
	}
	qi8 := make([]int8, M*K)
	qscale := make([]float32, M)
	for m, q := range queries {
		if len(q) != K {
			return nil, fmt.Errorf("gpu: batch query %d dim %d != index dim %d", m, len(q), K)
		}
		qscale[m] = quantizeRowInt8(q, qi8[m*K:(m+1)*K])
	}
	x.mu.Lock()
	defer x.mu.Unlock()
	defer func() {
		if r := recover(); r != nil {
			hits, err = nil, fmt.Errorf("gpu: topk scratch allocation failed: %v", r)
		}
	}()
	qi8Buf := x.b.dev.NewBufferInt8(qi8)
	qscaleBuf := x.b.dev.NewBufferFloats(qscale)
	scoreBuf := x.b.dev.NewBufferLen(M * N)
	idxBuf := gpu.NewBufferLenOf[int32](x.b.dev, M*k)
	valBuf := x.b.dev.NewBufferLen(M * k)
	mBuf := x.b.dev.NewBufferU32(uint32(M))
	kBuf := x.b.dev.NewBufferU32(uint32(k))
	defer func() {
		for _, b := range []gpu.Buffer{qi8Buf, qscaleBuf, scoreBuf, idxBuf, valBuf, mBuf, kBuf} {
			x.b.dev.ReleaseBuf(b)
		}
	}()

	if err := x.launchGEMM(qi8Buf, qscaleBuf, scoreBuf, M, N, K); err != nil {
		return nil, err
	}
	// One block per query; the kernel consumes winners in place, so scoreBuf is
	// scratch by the time it returns.
	if err := x.b.q.Launch(x.b.topk, gpu.LaunchConfig{
		GridX: uint32(M), GridY: 1, GridZ: 1, BlockX: 256, BlockY: 1, BlockZ: 1,
	}, gpu.Arg(scoreBuf), gpu.Arg(idxBuf), gpu.Arg(valBuf),
		gpu.Arg(mBuf), gpu.Arg(x.nbuf), gpu.Arg(kBuf)); err != nil {
		return nil, err
	}
	if err := x.b.q.Sync(); err != nil {
		return nil, err
	}
	idx := make([]int32, M*k)
	val := make([]float32, M*k)
	if err := gpu.Download(idxBuf, idx); err != nil {
		return nil, err
	}
	if err := gpu.Download(valBuf, val); err != nil {
		return nil, err
	}
	out := make([][]ann.Hit, M)
	for m := range M {
		row := make([]ann.Hit, 0, k)
		for j := range k {
			i := idx[m*k+j]
			if i < 0 {
				break
			}
			row = append(row, ann.Hit{Index: int(i), Score: float64(val[m*k+j])})
		}
		out[m] = row
	}
	return out, nil
}

// launchGEMM dispatches the batched W8A8 GEMM, picking the tiled kernel only when the
// batch is deep enough to fill its 16-row tile (see gemmTileMinM). Both kernels are
// bit-identical — int32 sums are associative — so this is purely a throughput choice and
// never changes a score.
func (x *cudaI8Index) launchGEMM(qi8Buf, qscaleBuf, outBuf gpu.Buffer, M, N, K int) error {
	if M >= gemmTileMinM {
		return x.b.q.Launch(x.b.gemmT, gpu.TileGrid(M, N),
			gpu.Arg(qi8Buf), gpu.Arg(qscaleBuf), gpu.Arg(x.codes), gpu.Arg(x.scales), gpu.Arg(outBuf),
			gpu.ArgValue(int32(M)), gpu.ArgValue(int32(N)), gpu.ArgValue(int32(K)))
	}
	if M == 1 {
		// gemmTileMinM is 2, so the naive GEMM only ever ran at M=1 — and at M=1 the
		// batch IS a single-query GEMV, whose kernel is warp-per-row and therefore
		// coalesced (be90aec: 3.3–6.0× the thread-per-row form). The naive GEMM still
		// has the defect the GEMV shed: one thread per (query, row), each walking its
		// row byte by byte. Route M=1 to the fast kernel instead of maintaining a
		// second slow one. Layouts already match — qscaleBuf is [1] here, which is
		// what gemv's scalar qscale binding expects, and out[j] is the same [N] row.
		return x.b.q.Run1D(x.b.gemv, x.n*32, 256,
			x.codes, qi8Buf, x.scales, x.kbuf, qscaleBuf, outBuf, x.nbuf)
	}
	totalBuf := x.b.dev.NewBufferU32(uint32(M * N))
	defer x.b.dev.ReleaseBuf(totalBuf)
	return x.b.q.Run1D(x.b.gemm, M*N, 256,
		x.codes, qi8Buf, x.scales, x.kbuf, x.nbuf, qscaleBuf, outBuf, totalBuf)
}
